exp: mono-light_darcy211
exp_root: ./outputs
seed: 0
dist_url: env://
data_name: darcy_211
data_root: ./dataset
train_batch_size: 4
val_batch_size: 4
rollout_history: 10
airfrans_subsampling: 32000
airfrans_eval_subsampling: 32000
airfrans_sampling_mode: all_surface
airfrans_eval_sampling_mode: all_surface
airfrans_raw_root: null
model_name: mono-light
normed_first_stage: false
out_droprate: 0.5
load_ckpt: null
strict_ckpt_load: false
freeze_loaded_params: false
loss_name: rL2
loss_weight: '1'
airfrans_surface_weight: 1.0
optimizer_name: AdamW
lr: 0.0014
weight_decay: 5.0e-05
scheduler_name: OneCycle
min_lr: 1.0e-05
warmup_epochs: 100
pct_start: 0.2
epoch: 500
log_print_interval_epoch: 1
model_save_interval_epoch: -1
grad_clip: 1000.0
n_train_vis: 4
rollout_autoreg_ratio: 0.0
